# Translation of Odoo Server.
# This file contains the translation of the following modules:
# 	* l10n_pe_validate_edi_document
#
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 14.0+e-20211213\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-01-18 02:59+0000\n"
"PO-Revision-Date: 2022-01-18 02:59+0000\n"
"Last-Translator: \n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Plural-Forms: \n"

#. module: l10n_pe_validate_edi_document
#: code:addons/l10n_pe_validate_edi_document/models/account_move.py:0
#, python-format
msgid "An error occurred while querying the status"
msgstr "Ocurrió un error al consultar el estado"

#. module: l10n_pe_validate_edi_document
#: code:addons/l10n_pe_validate_edi_document/models/account_move.py:0
#: code:addons/l10n_pe_validate_edi_document/models/account_move.py:0
#, python-format
msgid ""
"Check your firewall parameters, it is not being possible to connect with "
"server to sign invoices."
msgstr "Verifique los parámetros de su firewall, no es posible conectarse con el servidor para firmar facturas."

#. module: l10n_pe_validate_edi_document
#: code:addons/l10n_pe_validate_edi_document/models/account_move.py:0
#: code:addons/l10n_pe_validate_edi_document/models/account_move.py:0
#, python-format
msgid "Code not found"
msgstr "Codigo no encontrado"

#. module: l10n_pe_validate_edi_document
#: model:ir.model.fields,field_description:l10n_pe_validate_edi_document.field_account_move__display_name
msgid "Display Name"
msgstr "Nombre a Mostrar"

#. module: l10n_pe_validate_edi_document
#: model_terms:ir.ui.view,arch_db:l10n_pe_validate_edi_document.pg_view_move_get_edi_form
msgid "GET DOC EDI"
msgstr "Obtener Doc Sunat"

#. module: l10n_pe_validate_edi_document
#: model_terms:ir.ui.view,arch_db:l10n_pe_validate_edi_document.pg_view_move_get_edi_form
msgid "GET STATE EDI"
msgstr "Obtener Estado Doc"

#. module: l10n_pe_validate_edi_document
#: model:ir.model.fields,field_description:l10n_pe_validate_edi_document.field_account_move__id
msgid "ID"
msgstr ""

#. module: l10n_pe_validate_edi_document
#: model:ir.model,name:l10n_pe_validate_edi_document.model_account_move
msgid "Journal Entry"
msgstr "Asiento contable"

#. module: l10n_pe_validate_edi_document
#: model:ir.model.fields,field_description:l10n_pe_validate_edi_document.field_account_move____last_update
msgid "Last Modified on"
msgstr "Ultima Modificación en"

#. module: l10n_pe_validate_edi_document
#: code:addons/l10n_pe_validate_edi_document/models/account_move.py:0
#, python-format
msgid "SUNAT reponse: "
msgstr "Respuesta Sunat: "

#. module: l10n_pe_validate_edi_document
#: code:addons/l10n_pe_validate_edi_document/models/account_move.py:0
#: code:addons/l10n_pe_validate_edi_document/models/account_move.py:0
#, python-format
msgid ""
"The EDI document was successfully created and signed by the government."
msgstr "El documento EDI fue creado y firmado con éxito por el gobierno."

#. module: l10n_pe_validate_edi_document
#: code:addons/l10n_pe_validate_edi_document/models/account_move.py:0
#: code:addons/l10n_pe_validate_edi_document/models/account_move.py:0
#, python-format
msgid ""
"The URL provided for the IAP server is wrong, please go to  Settings --> "
"System Parameters and add the right URL to parameter l10n_pe_edi.endpoint."
msgstr "La URL proporcionada para el servidor SUNAT es incorrecta"

#. module: l10n_pe_validate_edi_document
#: code:addons/l10n_pe_validate_edi_document/models/account_move.py:0
#: code:addons/l10n_pe_validate_edi_document/models/account_move.py:0
#, python-format
msgid ""
"The URL provided to connect to the OSE is wrong, please check your "
"implementation."
msgstr "La URL proporcionada para conectarse a SUNAT es incorrecta."

#. module: l10n_pe_validate_edi_document
#: code:addons/l10n_pe_validate_edi_document/models/account_move.py:0
#: code:addons/l10n_pe_validate_edi_document/models/account_move.py:0
#, python-format
msgid "The XML generated is not valid."
msgstr "El XML generado no es válido"

#. module: l10n_pe_validate_edi_document
#: code:addons/l10n_pe_validate_edi_document/models/account_move.py:0
#: code:addons/l10n_pe_validate_edi_document/models/account_move.py:0
#, python-format
msgid ""
"The XML inside of the zip file is corrupted or has been altered, please "
"review the XML inside of the XML we are reading."
msgstr "El XML dentro del archivo zip está dañado o ha sido alterado"

#. module: l10n_pe_validate_edi_document
#: code:addons/l10n_pe_validate_edi_document/models/account_move.py:0
#: code:addons/l10n_pe_validate_edi_document/models/account_move.py:0
#, python-format
msgid ""
"The zip file is corrupted, please check that the zip we are reading is the "
"one you need."
msgstr "El archivo zip está dañado, verifique que el zip que estamos leyendo sea el correcto."

#. module: l10n_pe_validate_edi_document
#: code:addons/l10n_pe_validate_edi_document/models/account_move.py:0
#: code:addons/l10n_pe_validate_edi_document/models/account_move.py:0
#, python-format
msgid ""
"There are problems with the connection to the IAP server. Please try again "
"in a few minutes."
msgstr "Hay problemas con la conexión al servidor IAP. Vuelva a intentarlo"

#. module: l10n_pe_validate_edi_document
#: code:addons/l10n_pe_validate_edi_document/models/account_move.py:0
#: code:addons/l10n_pe_validate_edi_document/models/account_move.py:0
#, python-format
msgid ""
"There was an error while establishing the connection to the server, try "
"again and if it fails check the URL in the parameter l10n_pe_edi.endpoint."
msgstr "Hubo un error al establecer la conexión con el servidor, intente mas tarde."

#. module: l10n_pe_validate_edi_document
#: code:addons/l10n_pe_validate_edi_document/models/account_move.py:0
#: code:addons/l10n_pe_validate_edi_document/models/account_move.py:0
#, python-format
msgid ""
"Trying to send the invoice to the OSE the webservice returned a controlled "
"error, please try again later, the error is on their side not here."
msgstr "Intentando enviar la factura a sunat , el webservice retorno un error, intentelo mas tarde."
